// react-typescript/like-button.tsx
import "@material/mwc-button";
import * as React from "react";
import { useRef, useState } from "react";

declare global {
  namespace JSX {
    interface IntrinsicElements {
      "mwc-button": any;
    }
  }
}

export interface LikeButtonProps {
  likedText?: string;
}

export const LikeButton = (props: LikeButtonProps) => {
  const [liked, setLiked] = useState(false);
  const buttonRef = useRef(null);

  const { likedText, ...remainingProps } = props;
  const text = liked ? likedText ?? "Unlike" : "Like";

  const handleClick = () => {
    setLiked(!liked);
    buttonRef.current?.dispatchEvent(
      new CustomEvent("change", {
        detail: !liked,
        bubbles: true,
        cancelable: true,
        composed: true,
      })
    );
  };

  return (
    <mwc-button ref={buttonRef} {...remainingProps} onClick={handleClick}>
      {text}
    </mwc-button>
  );
};

// svelte/src/lib/LikeButton.svelte
<!--Add this line to your web component-->
<svelte:options tag="mc-like-button" />

<script lang="ts">
  import "@material/mwc-button";
  import { get_current_component } from "svelte/internal";

  let liked = false;
  const { liketext = "Like", unliketext = "Unlike", ...props } = $$props;
  const component = get_current_component();
  const handleClick = () => {
    liked = !liked;
    component?.dispatchEvent(new CustomEvent("change", { detail: liked }));
  };

  $: text = liked ? unliketext : liketext;
</script>

<mwc-button {...props} on:click={handleClick}>{text}</mwc-button>
